[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "SPOT"
authors = [{name = "Trasond", email = "barry_2001@stu.pku.edu.cn"}]
dynamic = ["version", "description"]
